# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "ohci_pci" "ehci_pci" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/131f5a5b-ac60-46f4-bd0a-53b16fddf35c";
      fsType = "ext4";
    };

  swapDevices = [ ];

  nix.maxJobs = 4;
  nix.buildCores = 4;

  services.virtualboxGuest.enable = true;
}
